stages:
  - validate
  - plan
  - apply

image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

variables:
  TF_VAR_aws_region: ${AWS_REGION}
  TF_VAR_aws_access_key: ${AWS_ACCESS_KEY_ID}
  TF_VAR_aws_secret_key: ${AWS_SECRET_ACCESS_KEY}
  TF_VAR_eb_workshop_app_type: ${EB_WORKSHOP_APP_TYPE}
  TF_VAR_eb_workshop_settings: ${EB_WORKSHOP_SETTINGS}
  TF_VAR_env_cidr_block: ${ENV_CIDR_BLOCK}

before_script:
  - export AWS_ACCESS_KEY=${TF_VAR_aws_access_key}
  - export AWS_SECRET_ACCESS_KEY=${TF_VAR_aws_secret_key}
  - rm -rf .terraform
  - terraform --version
  - terraform init
  
validate:
  stage: validate
  script:
    - terraform validate

plan:
  stage: plan
  script:
    - terraform plan -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply -input=false "planfile"
  dependencies:
    - plan
  when: manual