fail_fast: true
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.1
  hooks:
    - id: terraform_fmt
    # - id: checkov
    # - id: terraform_tflint
    - id: terraform_validate
    - id: terraform_docs
    - id: infracost_breakdown
      verbose: true 
      args:
        - --args=--path=./plan.json
        - --args=--out-file=infracost.json
        - --hook-config='.projects[].breakdown.totalMonthlyCost|tonumber <= 10'
        - --hook-config='.currency == "USD"'
