apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: terraform-infracost
  description: Terraform basic infrastructure and gauge cost
  annotations:
    github.com/project-slug: inrhythm-workshops/terraform-infracost

spec:
  type: service
  lifecycle: production
  owner: user:guest