configs:
  environments:
    - &main_agent_queue
      agents:
        queue: default

  pipelines:
    # trigger after merge code to main branch
    - &main_pipeline
      if: |
        build.branch == "main"
    
    # trigger on feature branches pull requests to main branch.
    - &feature_pipeline_main
      if: |
        build.pull_request.base_branch == "main"

    # trigger on feature branches
    - &feature_pipeline
      if: |
        build.branch != "main" && build.pull_request.base_branch != "main"
    
steps:
###############################################################
# Terraform execution - PLAN in main (on feature branches) #
###############################################################

  - label: Terraform_PLAN
    <<: *main_agent_queue
    # <<: *feature_pipeline
    command: "terraform plan"


##############################################################################
# Terraform execution - PLAN in main (on Pull requests to main branch) #
##############################################################################
  - label: Delay_10_seconds
    <<: *main_agent_queue
    # <<: *feature_pipeline_main
    commands: 
      - "sleep 10"
      
  # - wait:
    # <<: *feature_pipeline_main
 
  - block: ":rocket: Approve Terraform plan?"
    # <<: *feature_pipeline_main
    prompt: "Approve Terraform Plan?"
    blocked_state: running

  - label: Shell_output
    <<: *main_agent_queue
    # <<: *feature_pipeline_main
    commands:
      - echo "Pipeline run finished"

##########################################################################
# Terraform execution - APPLY in main (after merge to main branch) #
##########################################################################
  # - label: Terraform_APPLY_main
  #   <<: *main_agent_queue
  #   # <<: *main_pipeline
  #   command: "make applyAuto"
  #   env:
  #     TERRAFORM_ROOT_MODULE: "ec2"
  #     TERRAFORM_WORKSPACE: "dev"